### ISSUE TITLE
Want to add security policy 

### ISSUE THREAD

**Issue by Dipanita45** [ChandelAnish/fusionFLOW#117]
Want to add security policy to protect the website against the harms 

Please assign me the issue 
@ChandelAnish

**Comment by CogitoKunal** [comment]
@Dipanita45 how will you do that?
please mention approach

**Comment by Dipanita45** [comment]
I will create a security file in .md extension

**Comment by Dipanita45** [comment]
Please please assign me this issue

**Comment by CogitoKunal** [comment]
@Dipanita45 You are Assigned
