### ISSUE TITLE
Update the signup page

### ISSUE THREAD

**Issue by NK-Works** [ChandelAnish/fusionFLOW#14]
I can make the signup page better...
make sure to add the labels...
thansk:)

**Comment by ChandelAnish** [comment]
describe what you will do??

**Comment by ParasharDeb** [comment]
can i work on this? i can add the sliding from signup to signin transition that looks really good

**Comment by NK-Works** [comment]
> describe what you will do??

Well i can update the ui for the signup page and make it professional...
![image](https://github.com/user-attachments/assets/cdffddd4-9247-4a91-ba19-8f3600f6eb00)
somewhat like this....

**Comment by ParasharDeb** [comment]
![Screenshot 2024-10-05 172412](https://github.com/user-attachments/assets/1df021ec-6216-4dff-94f4-b7e8f5c040a8)
i can make something like this with a tranisition effect

**Comment by CogitoKunal** [comment]
Thank you for highlighting this issue. As it has been requested by multiple contributors, we are treating it as a priority. The contributor who resolves this issue first will be given priority for their efforts. We appreciate everyone's involvement and look forward to seeing the solution.
