### ISSUE TITLE
* Important Update: GirlScript Summer of Code Project Status*

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [ChandelAnish/fusionFLOW#35]
Dear Project Admins,

We hope this finds you well.

We are reaching out to you regarding the status of your project in the GirlScript Summer of Code program. We have noticed that there has been a period of inactivity on your project's repository.

We understand that unexpected circumstances can arise, and we want to ensure that your project continues to be a part of program. Please let us know if you would like to continue with your project. If so, we would appreciate it if you could actively participate.

If you have decided to discontinue your project, please let us know as soon as possible so that we can make necessary adjustments to the program.

Thank you for your understanding and cooperation.

The GirlScript Summer of Code Team

**Comment by CogitoKunal** [comment]
Project will be Active from now
