### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [ChandelAnish/fusionFLOW#44]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@ChandelAnish Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by tarunkumar2005** [comment]
@CogitoKunal I'm saying to add on website not documentation read properly.

**Comment by CogitoKunal** [comment]
it cant be added

**Comment by tarunkumar2005** [comment]
Okay 👍
