### ISSUE TITLE
UI and UX Enhancemnets | Addition of ProgressBar | Which will represent the Current height/Depth of the webpage.

### ISSUE THREAD

**Issue by Shariq2003** [ChandelAnish/fusionFLOW#69]
I want to implement the ProgressBar which will represent the current height/Depth of the webpage.
Just like on the GSSOC website

![image](https://github.com/user-attachments/assets/99123e79-1020-4783-adda-eb5540c2d8d6)

Look at the Top, an orange line

@CogitoKunal sir, please assign this to me.

**Comment by CogitoKunal** [comment]
You Are Assigned.

**Comment by Shariq2003** [comment]
> You Are Assigned.

Thanks sir,
