### ISSUE TITLE
Design a Landing page for fusionFlow

### ISSUE THREAD

**Issue by shubhagarwal1** [ChandelAnish/fusionFLOW#88]
<img width="1440" alt="Screenshot 2024-10-23 at 7 08 56 AM" src="https://github.com/user-attachments/assets/0ffc3a33-4064-4835-80e8-fcd5eef18057">

**Comment by CogitoKunal** [comment]
Issue is already Solved

**Comment by shubhagarwal1** [comment]
> Issue is already Solved

can you tell me another task, i really want to work on this
