### ISSUE TITLE
[Design] No About and Contact Us Page

### ISSUE THREAD

**Issue by Raj100** [ChandelAnish/fusionFLOW#97]
No About and Contact Us Page so make one for authenticity
<img width="1437" alt="Screenshot 2024-10-26 at 4 27 13 AM" src="https://github.com/user-attachments/assets/2db2c3ec-e45c-4f1f-83da-1cb05df96027">

**Comment by CogitoKunal** [comment]
Signin is Not Working at this time otherwise it works
